- README.md
- README.rst
Update readme with more information.
> Update readme with more information.

- README.rst
> fix build instruction example in README

- test/conftest.py
https://docs.pytest.org/en/latest/mark.html#update-marker-code
tests passed locally
> Use get_closest_marker instead of get_marker

- README.rst
- coach/docker/0.11.1/Dockerfile.mxnet
- coach/docker/0.11.1/Dockerfile.tf
- test/conftest.py
Updating Coach version to 0.11.1
> Updating Coach version to 0.11.1

- buildspec.yml
Add buildspec for RL. Tested in my own account. Although the gym integ tests failed, the build process is good.
> Add buildspec for RL

- buildspec.yml
> Fix typo for region argument

- buildspec.yml
- coach/docker/0.11.0/Dockerfile.mxnet
> Follow more recent redis installation instructions. 

- buildspec.yml
Get and pass PR number to remote test instance for GPU testing.
> Pass PR number to remote gpu tests

- buildspec-coach.yml
- coach/docker/1.0.0/Dockerfile.tf
Description of changes:
This commit adds a new Dockerfile to create containers with Coach updated version 1.0.0.
> add Dockerfile for Coach v1.0.0, add buildspec for Coach container

- buildspec-coach.yml
- coach/docker/1.0.0/Dockerfile.tf
Update Coach v1.0.0 buildspec file to skip gpu integration local tests
> Update Coach v1.0.0 buildspec file

- buildspec-coach.yml
- coach/docker/1.0.0/Dockerfile.tf
Skip creation of key-pair and gpu instance since we skip local gpu test
> Update Coach buildspec file

- buildspec-coach.yml
- coach/docker/1.0.0/Dockerfile.tf
Update Coach Dockerfile and buildspec to allow gpu test only in us-west-2
> Update Coach Dockerfile and buildspec to allow gpu test only in us-west-2

- buildspec-coach.yml
- coach/docker/1.0.0/Dockerfile.tf
Change local gpu test branch from 'coach-1.0.0' to 'master'
> Change local gpu test branch from 'coach-1.0.0' to 'master'

- buildspec-coach.yml
- coach/docker/1.0.0/Dockerfile.tf
Change gpu remote test branch to master
> Change gpu remote test branch to master

- buildspec-ray.yml
- ray/docker/0.8.2/Dockerfile.tf
- test/resources/ray_cartpole/train_ray.py
This commit adds a new Dockerfile to create containers with RLLib updated version 0.8.2.
> add Dockerfile for RLLib v0.8.2, add buildspec for RLLib container

- src/vw-serving/src/vw_serving/serve.py
> add support for batch inference - JSON lines & CSV input & output

- README.rst
add image urls for updated images
> add image urls for updated images

- README.rst
* Improves readability of the README file.
> Minor: add newline to README to correct display of PyTorch containers.

- buildspec-ray.yml
- ray/docker/1.0.0/Dockerfile.tf
- ray/docker/1.0.0/Dockerfile.torch
> Update Ray version to 1.0.0

- ray/docker/1.0.0/Dockerfile.tf
- ray/docker/1.0.0/Dockerfile.torch
- test/resources/ray_cartpole/train_ray_tf.py
- test/resources/ray_cartpole/train_ray_torch.py
* Add pip install dataclasses for Python3.6 environment.
* Update training code to latest Ray API specs.
> Ray 1.0 docker image related fixes

- buildspec-ray.yml
- ray/docker/1.0.0/Dockerfile.tf
- ray/docker/1.0.0/Dockerfile.torch
- ray/docker/1.1.0/Dockerfile.tf
- ray/docker/1.1.0/Dockerfile.torch
- test/resources/ray_cartpole/train_ray_tf.py
- test/resources/ray_cartpole/train_ray_torch.py
Update to use Ray versions 1.0.0 and 1.1.0
> Add Ray 1.0 and Ray 1.1 docker containers 

- buildspec-ray.yml
> Remove ECR delete commands

- README.rst
Adds Ray 1.1.0 docker image links to README.
> Add Ray 1.1.0 images to README

- buildspec-vw.yml
- vw/docker/8.7.0/Dockerfile
> fix VW container build

- buildspec-ray.yml
- coach/docker/1.0.0/Dockerfile.tf
- ray/docker/0.8.5/Dockerfile.tf
- ray/docker/0.8.5/Dockerfile.torch
- vw/docker/8.7.0/Dockerfile
> Fix Ray 0.8.5 container build

- buildspec-ray.yml
- ray/docker/0.8.5/Dockerfile.torch
Reverts aws/sagemaker-rl-container#65
> Revert "Fix Ray 0.8.5 container build"

- README.rst
We have generated new images for Ray 1.6.0. Added links of these images in README.
> Modify README with new Ray (1.6.0) images link

- README.rst
- ray/docker/1.6.0/Dockerfile
- ray/docker/1.6.0/Generate docker image.ipynb
Upload Ray 1.6.0 Dockerfile. Tested with Tensorflow and PyTorch, on both cpu and gpu versions.
Upload a jupyter notebook which consumes this Dockerfile to generate Docker.
> Add Ray 1.6.0 Dockerfile and a notebook example
